In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('out.csv', index_col=0)

In [4]:
df.shape

(1811, 71)

In [5]:
df.head()

accX_1  accY_1  accZ_1  accResultant_1  gyrX_1  gyrY_1  gyrZ_1  accX_2  \
0    0.02   -0.87    2.06            2.24   -5.92    1.57   -0.04    0.03   
1    0.03   -0.87    2.13            2.31   -1.47    0.95   -0.94    0.03   
2    0.03   -0.88    2.09            2.27   -6.20    4.59    2.05    0.04   
3    0.04   -0.87    2.07            2.25  -10.70    1.66    0.73    0.04   
4    0.04   -0.87    2.04            2.22   -9.71    1.54    0.70    0.03   

   accY_2  accZ_2  ...  gyrY_9  gyrZ_9  accX_10  accY_10  accZ_10  \
0   -0.87    2.08  ...    0.88    0.25     0.03    -0.87     2.02   
1   -0.87    2.07  ...    0.95    1.46     0.04    -0.86     2.06   
2   -0.87    2.07  ...   10.86   22.49    -0.03     0.08     0.99   
3   -0.87    2.04  ...    1.27    0.25    -0.03     0.07     1.00   
4   -0.87    2.04  ...    1.29    0.20    -0.03     0.07     1.00   

   accResultant_10  gyrX_10  gyrY_10  gyrZ_10  isFall  
0             2.20     0.26     1.16     0.18     0.0  
1             2.24    -4.30     2.23     0.65     0.0  
2             0.99    -7.09     1.27     0.25     1.0  
3             1.00    -6.25     1.29     0.20     1.0  
4             1.00    -6.25     1.31     0.28     1.0  

[5 rows x 71 columns]

In [6]:
df.filter(regex='tilt', axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1811 rows x 0 columns]

In [8]:
window_size = 10

In [9]:
df.to_numpy()

array([[ 0.02, -0.87,  2.06, ...,  1.16,  0.18,  0.  ],
       [ 0.03, -0.87,  2.13, ...,  2.23,  0.65,  0.  ],
       [ 0.03, -0.88,  2.09, ...,  1.27,  0.25,  1.  ],
       ...,
       [ 0.15, -0.85,  1.91, ...,  0.67,  4.87,  0.  ],
       [ 0.05, -0.84,  1.76, ...,  1.22,  1.07,  0.  ],
       [ 0.03, -0.79,  1.59, ...,  1.47, -2.39,  0.  ]])

In [10]:
# generate C3
accX = df.filter(regex='accX', axis=1).to_numpy()
accX_max = np.amax(accX, axis=1)

In [11]:
accY = df.filter(regex='accY', axis=1).to_numpy()
accY_max = np.amax(accY, axis=1)

In [12]:
accZ = df.filter(regex='accZ', axis=1).to_numpy()
accZ_max = np.amax(accZ, axis=1)

In [13]:
accX_min = np.amin(accX, axis=1)
accY_min = np.amin(accY, axis=1)
accZ_min = np.amin(accZ, axis=1)

In [14]:
accX_peak = accX_max - accX_min
accY_peak = accY_max - accY_min
accZ_peak = accZ_max - accZ_min

In [15]:
accX_peak[:10]

array([0.03, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.11, 0.11, 0.11])

In [16]:
accY_peak[:10]

array([0.  , 0.02, 1.24, 1.23, 1.23, 1.23, 1.23, 1.22, 1.19, 0.96])

In [17]:
accZ_peak[:10]

array([0.06, 0.1 , 1.17, 1.17, 1.17, 1.17, 1.17, 1.07, 1.03, 1.01])

In [18]:
C3_acc = np.sqrt(accX_peak**2 + accY_peak**2 + accZ_peak**2)

In [19]:
# generate C1
accR = df.filter(regex='Resultant', axis=1).to_numpy()
C1_acc = np.sqrt(np.sum(accR**2, axis=1))

In [20]:
# generate C2
accXY = df.filter(regex='acc(X|Y)', axis=1).to_numpy()
C2_acc = np.sqrt(np.sum(accXY**2, axis=1))

In [21]:
# generate C4
angleZ = np.sqrt(np.sum(accX, axis=1)**2 + np.sum(accZ, axis=1)**2)
vertical = -np.sum(accY, axis=1)
C4_acc = np.arctan2(angleZ, vertical)

In [22]:
gyr_df = df.filter(regex='gyr', axis=1)
gyr_df.head(5)

gyrX_1  gyrY_1  gyrZ_1  gyrX_2  gyrY_2  gyrZ_2  gyrX_3  gyrY_3  gyrZ_3  \
0   -5.92    1.57   -0.04   -7.55    1.35    0.54   -8.21    1.27    0.70   
1   -1.47    0.95   -0.94   -7.15    1.39    1.19   -3.23    2.21   -1.09   
2   -6.20    4.59    2.05  -10.70    1.66    0.73   -9.71    1.54    0.70   
3  -10.70    1.66    0.73   -9.71    1.54    0.70   -2.81    1.25    0.28   
4   -9.71    1.54    0.70   -2.81    1.25    0.28  -10.79    1.81    1.13   

   gyrX_4  ...  gyrZ_7  gyrX_8  gyrY_8  gyrZ_8  gyrX_9  gyrY_9  gyrZ_9  \
0   -6.60  ...    0.31   -8.74    1.10   -0.33   -2.98    0.88    0.25   
1   -6.75  ...    0.51   -5.69   -3.38   -5.09   -5.75    0.95    1.46   
2   -2.81  ...    4.70 -128.66    7.04   10.26 -258.12   10.86   22.49   
3  -10.79  ...   10.26 -258.12   10.86   22.49   -7.09    1.27    0.25   
4  -33.13  ...   22.49   -7.09    1.27    0.25   -6.25    1.29    0.20   

   gyrX_10  gyrY_10  gyrZ_10  
0     0.26     1.16     0.18  
1    -4.30     2.23     0.65  
2    -7.09     1.27     0.25  
3    -6.25     1.29     0.20  
4    -6.25     1.31     0.28  

[5 rows x 30 columns]

In [23]:
gyr = gyr_df.to_numpy()
gyr_r = []

for i in range(len(gyr)):
    elem = []
    for j in range(window_size):
        elem.append(np.linalg.norm(gyr[i, j*3:j*3 + 3]))
    gyr_r.append(elem)

gyrR = np.array(gyr_r)

In [24]:
gyr_min = np.amin(gyr_r, axis=1)

In [25]:
gyr_max = np.amax(gyr_r, axis=1)

In [26]:
# generate C3
gyrX = df.filter(regex='gyrX', axis=1).to_numpy()
gyrX_max = np.amax(gyrX, axis=1)

In [27]:
gyrY = df.filter(regex='gyrY', axis=1).to_numpy()
gyrY_max = np.amax(gyrY, axis=1)

In [28]:
gyrZ = df.filter(regex='gyrZ', axis=1).to_numpy()
gyrZ_max = np.amax(gyrZ, axis=1)

In [29]:
gyrX_min = np.amin(gyrX, axis=1)
gyrY_min = np.amin(gyrY, axis=1)
gyrZ_min = np.amin(gyrZ, axis=1)

In [30]:
gyrX_peak = gyrX_max - gyrX_min
gyrY_peak = gyrY_max - gyrY_min
gyrZ_peak = gyrZ_max - gyrZ_min

In [31]:
C3_gyr = np.sqrt(gyrX_peak**2 + gyrY_peak**2 + gyrZ_peak**2)

In [32]:
# generate C1
C1_gyr = np.sqrt(np.sum(gyrR**2, axis=1))

In [33]:
# generate C2
gyrXY = df.filter(regex='gyr(X|Y)', axis=1).to_numpy()
C2_gyr = np.sqrt(np.sum(gyrXY**2, axis=1))

In [34]:
# generate C4
angle_gyr_Z = np.sqrt(np.sum(gyrX, axis=1)**2 + np.sum(gyrZ, axis=1)**2)
gyr_vertical = -np.sum(gyrY, axis=1)
C4_gyr = np.arctan2(angle_gyr_Z, gyr_vertical)

In [35]:
print(C1_acc.shape)
print(C2_acc.shape)
print(C3_acc.shape)
print(C4_acc.shape)

(1811,)
(1811,)
(1811,)
(1811,)


In [36]:
print(C1_gyr.shape)
print(C2_gyr.shape)
print(C3_gyr.shape)
print(C4_gyr.shape)

(1811,)
(1811,)
(1811,)
(1811,)


In [37]:
results = []

for i in range(len(C1_gyr)):
    elem = []
    for attr in [C1_acc, C2_acc, C3_acc, C4_acc, C1_gyr, C2_gyr, C3_gyr, C4_gyr]:
        elem.append(attr[i])
    results.append(elem)

results = np.array(results)

In [38]:
new_df = pd.DataFrame(results, columns = ['C1_acc', 'C2_acc', 'C3_acc', 'C4_acc', 'C1_gyr', 'C2_gyr', 'C3_gyr', 'C4_gyr'])

In [39]:
new_df.head()

C1_acc    C2_acc    C3_acc    C4_acc      C1_gyr      C2_gyr      C3_gyr  \
0  7.061579  2.753144  0.067082  1.170361   20.909613   20.878003    9.107387   
1  7.121994  2.744048  0.102470  1.175235   22.343852   21.577783   13.235415   
2  6.658694  2.395955  1.707776  1.260583  298.144178  297.058409  256.456947   
3  6.339188  2.229596  1.700529  1.290640  298.105698  297.026795  256.461288   
4  6.010225  2.053874  1.700529  1.324871  297.976652  296.898046  256.461288   

     C4_gyr  
0  1.770244  
1  1.761841  
2  1.639897  
3  1.633672  
4  1.633542

In [40]:
new_df['isFall'] = df['isFall']
new_df.head(20)

C1_acc    C2_acc    C3_acc    C4_acc      C1_gyr      C2_gyr  \
0   7.061579  2.753144  0.067082  1.170361   20.909613   20.878003   
1   7.121994  2.744048  0.102470  1.175235   22.343852   21.577783   
2   6.658694  2.395955  1.707776  1.260583  298.144178  297.058409   
3   6.339188  2.229596  1.700529  1.290640  298.105698  297.026795   
4   6.010225  2.053874  1.700529  1.324871  297.976652  296.898046   
5   5.674011  1.861639  1.700529  1.364737  297.879122  296.800983   
6   5.316578  1.647331  1.700529  1.410904  297.927704  296.849731   
7   4.882325  1.400857  1.626469  1.463834  297.792553  296.716224   
8   4.456927  1.108242  1.577688  1.526674  295.989590  294.917435   
9   4.013951  0.738038  1.397784  1.598542  290.328468  289.273377   
10  3.569832  0.434626  0.961405  1.662350  260.043625  259.068199   
11  5.188786  1.824390  1.551966  1.285528  174.069537  173.378020   
12  7.134143  2.752817  0.020000  1.175019   19.323747   19.133884   
13  5.714385  2.117451  2.526539  1.314387  303.424950  302.567872   
14  3.162278  0.239583  0.014142  1.639654   20.450181   20.395529   
15  5.248543  1.808839  1.701058  1.298373  215.387749  214.743904   
16  6.443827  2.165664  1.772089  1.306104  314.411843  313.520247   
17  6.101877  1.984591  1.772089  1.340128  314.425475  313.559444   
18  5.735573  1.785105  1.765276  1.379406  314.478092  313.612545   
19  5.352822  1.566014  1.765276  1.424860  314.483174  313.618639   

        C3_gyr    C4_gyr  isFall  
0     9.107387  1.770244     0.0  
1    13.235415  1.761841     0.0  
2   256.456947  1.639897     1.0  
3   256.461288  1.633672     1.0  
4   256.461288  1.633542     1.0  
5   256.484627  1.632898     1.0  
6   253.209890  1.632204     1.0  
7   253.209890  1.631536     1.0  
8   253.209890  1.632128     1.0  
9   253.209890  1.633763     1.0  
10  253.209890  1.640023     0.0  
11  123.273732  1.571248     0.0  
12    6.151049  1.785599     0.0  
13  252.750141  1.609783     0.0  
14    1.275696  1.783964     0.0  
15  130.634722  1.566017     0.0  
16  258.448081  1.626988     1.0  
17  256.668028  1.635930     1.0  
18  253.587265  1.634846     1.0  
19  253.580960  1.635217     1.0

In [41]:
new_df.to_csv('extra_features.csv')